export LC_ALL=en_US.UTF-8

export ANDROID_HOME=$HOME/Android/Sdk
export AndroidSdkDirectory=$ANDROID_HOME
export DOTNET_ROOT=/opt/dotnet

export VISUAL="nvim"
export EDITOR="nvim"
export TERMINAL="st"
export PAGER="less"
export BROWSER="chromium"
export OPENER="xdg-open"
#export PATH="${PATH}:/home/mofasa/.local/bin:/usr:/usr/lib/python3.10/site-packages/opencv_python-4.5.5.62-py3.10-linux-x86_64.egg/cv2"
#export PATH="${PATH}:/home/mofasa/.local/bin:/opt/dotnet:$HOME/Android/Sdk/cmdline-tools/latest/bin:$HOME/Android/Sdk/platform-tools"
export PATH="${PATH}:/home/mofasa/.local/bin:/opt/dotnet:/home/mofasa/.deno/bin:/home/mofasa/.dotnet/tools:/home/mofasa/go/bin:/opt/flutter/bin:/opt/VSCode-linux-x64/bin:$HOME/.rbenv/shims:$HOME/.rbenv/bin:/opt/Antigravity/bin:/home/mofasa/.cargo/bin:/opt/audiorelay/bin"

export PICTURES=~/Pictures
export SITES="chromium"

export ASPNETCORE_ENVIRONMENT="Development"


export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib64/pkgconfig

export BUNDLE_GEMFILE=
export BUNDLE_IGNORE_CONFIGURE_RUBY_VERSION=true

# eval $(minikube docker-env)
#export DOCKER_TLS_VERIFY="1"
#export DOCKER_HOST="tcp://192.168.49.2:2376"
#export DOCKER_CERT_PATH="/home/mofasa/.minikube/certs"
#export MINIKUBE_ACTIVE_DOCKERD="minikube"

#for idea
export _JAVA_AWT_WM_NONREPARENTING=1

#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

#export LD_PRELOAD=/usr/lib/pipewire-0.3/libpipewire-module-rt.so

export LF_BOOKMARK_PATH=~/.config/book_marks

#export VIRTUAL_ENV=/home/mofasa/miniconda3/envs/TM/bin/python3.10-config

export LF_ICONS="\
di=:\
fi=:\
ln=:\
or=:\
ex=:\
*.vimrc=:\
*.viminfo=:\
*.gitignore=:\
*.c=:\
*.cc=:\
*.cs=󰌛:\
*.clj=:\
*.coffee=:\
*.cpp=:\
*.css=:\
*.d=:\
*.dart=:\
*.erl=:\
*.exs=:\
*.fs=:\
*.go=:\
*.h=:\
*.hh=:\
*.hpp=:\
*.hs=:\
*.html=:\
*.java=:\
*.jl=:\
*.js=:\
*.json=:\
*.lua=:\
*.md=:\
*.php=:\
*.pl=:\
*.pro=:\
*.py=:\
*.rb=:\
*.rs=:\
*.scala=:\
*.ts=:\
*.vim=:\
*.cmd=:\
*.ps1=:\
*.sh=:\
*.bash=:\
*.zsh=:\
*.fish=:\
*.tar=:\
*.tgz=:\
*.arc=:\
*.arj=:\
*.taz=:\
*.lha=:\
*.lz4=:\
*.lzh=:\
*.lzma=:\
*.tlz=:\
*.txz=:\
*.tzo=:\
*.t7z=:\
*.zip=:\
*.z=:\
*.dz=:\
*.gz=:\
*.lrz=:\
*.lz=:\
*.lzo=:\
*.xz=:\
*.zst=:\
*.tzst=:\
*.bz2=:\
*.bz=:\
*.tbz=:\
*.tbz2=:\
*.tz=:\
*.deb=:\
*.rpm=:\
*.jar=:\
*.war=:\
*.ear=:\
*.sar=:\
*.rar=:\
*.alz=:\
*.ace=:\
*.zoo=:\
*.cpio=:\
*.7z=:\
*.rz=:\
*.cab=:\
*.wim=:\
*.swm=:\
*.dwm=:\
*.esd=:\
*.jpg=:\
*.jpeg=:\
*.mjpg=:\
*.mjpeg=:\
*.gif=:\
*.bmp=:\
*.pbm=:\
*.pgm=:\
*.ppm=:\
*.tga=:\
*.xbm=:\
*.xpm=:\
*.tif=:\
*.tiff=:\
*.png=:\
*.svg=:\
*.svgz=:\
*.mng=:\
*.pcx=:\
*.mov=:\
*.mpg=:\
*.mpeg=:\
*.m2v=:\
*.mkv=:\
*.webm=:\
*.ogm=:\
*.mp4=:\
*.m4v=:\
*.mp4v=:\
*.vob=:\
*.qt=:\
*.nuv=:\
*.wmv=:\
*.asf=:\
*.rm=:\
*.rmvb=:\
*.flc=:\
*.avi=:\
*.fli=:\
*.flv=:\
*.gl=:\
*.dl=:\
*.xcf=:\
*.xwd=:\
*.yuv=:\
*.cgm=:\
*.emf=:\
*.ogv=:\
*.ogx=:\
*.aac=:\
*.au=:\
*.flac=:\
*.m4a=:\
*.mid=:\
*.midi=:\
*.mka=:\
*.mp3=:\
*.mpc=:\
*.ogg=:\
*.ra=:\
*.wav=:\
*.oga=:\
*.opus=:\
*.spx=:\
*.xspf=:\
*.pdf=:\
*.nix=:\
"
